---
title: "Project Attrition"
author: "Anthony Yeung"
date: "April 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Load Library
```
library(dplyr)
library(plyr)
library(ggplot2)

```

### Read Attrition csv file
```
atr <- read.csv("C:/Users/AY/Desktop/attrition.csv", header=TRUE)

names(atr)
str(atr)



```

### Replacing Attrition column yes and no with 1 and 0

```
atr$Attrition <- revalue(atr$Attrition, c("Yes"=1))
atr$Attrition<- revalue(atr$Attrition, c("No"=0))

```

### Replacing Attrition column with atr$Attrition 

```
Attrition <- atr$Attrition

```

### Change Attrition column into numeric

```
atr$Attrition <- as.numeric(as.character(atr$Attrition))

atr[1:3,1:3]
str(atr)

```

### Replacing Gender column Female and Male with 1 and 0

```
atr$Gender <- revalue(atr$Gender, c("Female"=1))
atr$Gender <- revalue(atr$Gender, c("Male"=0))

```

### Replacing Gender column with atr$Gender

```
Gender <- atr$Gender

```


### Change Gender column into numeric

```
atr$Gender <- as.numeric(as.character(atr$Gender))

atr[1:3,11:13]
str(atr)

```

### Replacing MaritalStatus column Single and Married with 1 and 0

```
atr$MaritalStatus <- revalue(atr$MaritalStatus, c("Single"=1))
atr$MaritalStatus <- revalue(atr$MaritalStatus, c("Married"=0))

```

### Replacing MaritalStatus column with atr$MaritalStatus

```
MaritalStatus <- atr$MaritalStatus

```

### Change MaritalStatus column into numeric

```
atr$MaritalStatus <- as.numeric(as.character(atr$MaritalStatus))

atr[1:3,17:19]
str(atr)

```
### Replacing Over18 column Y with 1 

```
atr$Over18 <- revalue(atr$Over18, c("Y"=1))

```

### Replacing Over18 column with atr$Over18

```
Over18 <- atr$Over18

```

### Change Over18 column into numeric

```
atr$Over18 <- as.numeric(as.character(atr$Over18))

atrstr(atr)[1:3,21:23]
str(atr)

```

### Replacing OverTime column Yes and No with 1 and 0

```

atr$OverTime <- revalue(atr$OverTime, c("Yes"=1))
atr$OverTime <- revalue(atr$OverTime, c("No"=0))

```

### Replacing OverTime column with atr$OverTime

```
OverTime <- atr$OverTime

```

### Change Overtime column into numeric

```
atr$OverTime <- as.numeric(as.character(atr$Overtime))

atr[1:3,22:24]
str(atr)

```

## **Correlation Calculation**

cor(atr$Age, atr$Attrition,atr$DailyRate)






```
corr_age<- cor(atr$Attrition,atr$Age )
corr_age


corr_DailyRate <- cor(atr$Attrition, atr$DailyRate)
corr_DailyRate


corr_DistanceFromHome <- cor(atr$Attrition, atr$DistanceFromHome)
corr_DistanceFromHome

corr_Education <- cor(atr$Attrition, atr$Education)
corr_Education

corr_EmployeeCount <- cor(atr$Attrition, atr$EmployeeCount)
corr_EmployeeCount

corr_EmployeeNumber <- cor(atr$Attrition, atr$EmployeeNumber)
corr_EmployeeNumber

corr_EnvironmentSatisfaction <- cor(atr$Attrition, atr$EnvironmentSatisfaction)
corr_EnvironmentSatisfaction

corr_Gender <- cor(atr$Attrition, atr$Gender)
corr_Gender

corr_HourlyRate <- cor(atr$Attrition, atr$HourlyRate)
corr_HourlyRate

corr_JobInvolvement <- cor(atr$Attrition, atr$JobInvolvement)
corr_JobInvolvement 

corr_JobLevel <- cor(atr$Attrition, atr$JobLevel)
corr_JobLevel

corr_JobSatisfaction <- cor(atr$Attrition, atr$JobSatisfaction)
corr_JobSatisfaction

corr_MaitalStatus <- cor(atr$Attrition, atr$MaritalStatus)
corr_MaitalStatus

corr_MonthlyIncome <- cor(atr$Attrition, atr$MonthlyIncome)
corr_MonthlyIncome 

corr_MonthlyRate <- cor(atr$Attrition, atr$MonthlyRate)
corr_MonthlyRate

corr_NumCompaniesWorked <- cor(atr$Attrition, atr$NumCompaniesWorked)
corr_NumCompaniesWorked 

corr_Over18 <- cor(atr$Attrition, atr$Over18)
corr_Over18

corr_OverTime <- cor(atr$Attrition, atr$OverTime)
corr_OverTime

corr_PercentSalaryHike <- cor(atr$Attrition, atr$PercentSalaryHike)
corr_PercentSalaryHike

corr_PerformanceRating <- cor(atr$Attrition, atr$PerformanceRating)
corr_PerformanceRating

corr_RelationshipSatisfaction <- cor(atr$Attrition, atr$RelationshipSatisfaction)
corr_RelationshipSatisfaction

corr_StandardHours <- cor(atr$Attrition, atr$StandardHours)
corr_StandardHours 

corr_StockOptionLevel <- cor(atr$Attrition, atr$StockOptionLevel)
corr_StockOptionLevel

corr_TotalWorkingYears <- cor(atr$Attrition, atr$TotalWorkingYears)
corr_TotalWorkingYears

corr_TrainingTimesLastYear <- cor(atr$Attrition, atr$TrainingTimesLastYear)
corr_TrainingTimesLastYear 

corr_WorkLifeBalance <- cor(atr$Attrition, atr$WorkLifeBalance)
corr_WorkLifeBalance 

corr_YearsAtCompany <- cor(atr$Attrition, atr$YearsAtCompany)
corr_YearsAtCompany 

corr_YearsInCurrentRole <- cor(atr$Attrition, atr$YearsInCurrentRole)
corr_YearsInCurrentRole

corr_YearsSinceLastPromotion <- cor(atr$Attrition, atr$YearsSinceLastPromotion)
corr_YearsSinceLastPromotion 

corr_YearsWithCurrManager <- cor(atr$Attrition, atr$YearsWithCurrManager)
corr_YearsWithCurrManager

```


## **Multiple Regesssion of Attrition against all variables**  

```
MR_atr_select <- lm(Attrition ~ Age+ DailyRate+ DistanceFromHome+ Education+ EmployeeNumber+ EnvironmentSatisfaction+ Gender+ HourlyRate+ JobInvolvement+ JobLevel+ JobSatisfaction+ MonthlyIncome+ MonthlyRate+ NumCompaniesWorked+ PercentSalaryHike+ PerformanceRating+ RelationshipSatisfaction+ StockOptionLevel+ TotalWorkingYears+ TrainingTimesLastYear+ WorkLifeBalance+ YearsAtCompany+ YearsInCurrentRole+ YearsSinceLastPromotion+ YearsWithCurrManager, data=atr)

MR_atr_select

summary(MR_atr_select)

```







###**Re Run Multiple Regression Model after eliminating all insignificants varaibles**

```

MR_atr_select <- lm(Attrition ~ Age+  DistanceFromHome+ EnvironmentSatisfaction+ JobInvolvement+ JobSatisfaction+ MonthlyIncome+ NumCompaniesWorked+ StockOptionLevel, data=atr)

MR_atr_select

summary(MR_atr_select)

```

##**Attrition Multiple Regression Model** 

```
Regression maodel is

Atttrition = 0.7444+
(-0.00494)*(Age)+
(0.003806)*(distanceFroHome)+
(-0.003503)*(EnvironmentSatisfaction)+
(-0.06747)*(JobInvolemtn)+
(-0.03369)*(JobStatisfaction)+
(-0.00000899)*(MonthlyIncome)+
(0.01496)*(NumCompaniesWorked)+
(-0.05806)*(StockOptionLevel)


```




###Question C Correlation between age and Monthly Income

```
#Relationship of age and Income

cor_age_income<- cor(atr$Age, atr$MonthlyIncome)
cor_age_income

```
### **Correlation between Age and Monthly Income is 0.49785**




##ggplot of Age and Monthly Income

```
ggplot(atr,aes(x=atr$Age,y=atr$MonthlyIncome))+geom_point(color="blue")+
xlab("Age")+
ylab("Monthly Income")+
ggtitle("                  Age and Monthly Income")+
stat_smooth(method="lm", color="green")

```





##ggplot age variable on histogram
```
ggplot(atr,aes(x=atr$Age))+geom_histogram(binwidth=1,color="red", fill="yellow")+
xlab("Age")+
ggtitle("Age")
```

##ggplot Monthly Income variable on histogram

```
ggplot(atr,aes(x=atr$MonthlyIncome))+geom_histogram(binwidth=1000,color="blue", fill="red")+
xlab("Monthly Income")+
ggtitle("Monthly Income")


```
##ggplot Gender variable on histogram

```
ggplot(atr,aes(x=atr$Education))+geom_histogram(binwidth=1,color="blue", fill="brown")+
xlab("Education")+
ggtitle("Education")

```




















## **Principal Component Analysis**
####** PCA descriptive statistics**
```
atr_select <- atr %>%  select(Age, Attrition, DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,Gender, HourlyRate,JobInvolvement, JobLevel, JobSatisfaction, MonthlyIncome, MonthlyRate,NumCompaniesWorked, PercentSalaryHike, PerformanceRating,RelationshipSatisfaction, StockOptionLevel,TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany,YearsInCurrentRole, YearsSinceLastPromotion,YearsWithCurrManager)

summary(atr_select)
cor(atr_select)

```
####**Correlation matrix of Attrition against all variables**
```
cor(atr_select,atr_select$Attrition)

```
#### **Attrition has positive correlation with 4 variables**

```
DistanceFromHome          0.077923583
MonthlyRate               0.015170213
NumCompaniesWorked        0.043493739
PerformanceRating         0.002888752

                                [,1]
Age                      -0.159205007
Attrition                 1.000000000
DailyRate                -0.056651992
DistanceFromHome          0.077923583
Education                -0.031372820
EmployeeNumber           -0.010577243
EnvironmentSatisfaction  -0.103368978
Gender                   -0.029453253
HourlyRate               -0.006845550
JobInvolvement           -0.130015957
JobLevel                 -0.169104751
JobSatisfaction          -0.103481126
MonthlyIncome            -0.159839582
MonthlyRate               0.015170213
NumCompaniesWorked        0.043493739
PercentSalaryHike        -0.013478202
PerformanceRating         0.002888752
RelationshipSatisfaction -0.045872279
StockOptionLevel         -0.137144919
TotalWorkingYears        -0.171063246
TrainingTimesLastYear    -0.059477799
WorkLifeBalance          -0.063939047
YearsAtCompany           -0.134392214
YearsInCurrentRole       -0.160545004
YearsSinceLastPromotion  -0.033018775
YearsWithCurrManager     -0.156199316


```
### PCA
```
atr_select <- princomp(atr_select, score=TRUE, cor=TRUE)

summary(atr_select)

```


### **Screeplot of PCA**

```

plot(atr_select)

```

### **Scree Plot of PCA**

```
screeplot(atr_select,type="l",main="Scree Plot")

```












